/mnt/home/20236065/anaconda3/lib/python3.10/site-packages/glfw/__init__.py:916: GLFWError: (65544) b'X11: The DISPLAY environment variable is missing'
  warnings.warn(message, GLFWError)
===== HYPERPARAMTERS =====
Domain and task: walker - run
Discount factor gamma: 0.99
Target update weight tau: 0.005
Learning rate: 0.0001
Number of episodes: 10000
Random seed: 0
Temperature alpha: automatic
Episode: 0, steps: 1000, return: 24.98
Test in episode: 0, average return: 24.98
Episode: 1, steps: 2000, return: 28.39
Episode: 2, steps: 3000, return: 29.19
Episode: 3, steps: 4000, return: 24.99
Episode: 4, steps: 5000, return: 29.45
Episode: 5, steps: 6000, return: 50.14
Episode: 6, steps: 7000, return: 27.41
Episode: 7, steps: 8000, return: 28.14
Episode: 8, steps: 9000, return: 27.17
Episode: 9, steps: 10000, return: 24.69
Episode: 10, steps: 11000, return: 10.53
Episode: 11, steps: 12000, return: 20.08
Episode: 12, steps: 13000, return: 23.62
Episode: 13, steps: 14000, return: 25.2
Episode: 14, steps: 15000, return: 10.52
Episode: 15, steps: 16000, return: 23.7
Episode: 16, steps: 17000, return: 27.96
Episode: 17, steps: 18000, return: 26.03
Episode: 18, steps: 19000, return: 25.26
Episode: 19, steps: 20000, return: 27.52
Episode: 20, steps: 21000, return: 25.37
Episode: 21, steps: 22000, return: 26.01
Episode: 22, steps: 23000, return: 15.62
Episode: 23, steps: 24000, return: 22.33
Episode: 24, steps: 25000, return: 23.37
Episode: 25, steps: 26000, return: 23.83
Episode: 26, steps: 27000, return: 23.07
Episode: 27, steps: 28000, return: 24.34
Traceback (most recent call last):
  File "/mnt/home/20236065/EE619-project03/MINE/ee619/train.py", line 204, in <module>
    main(**vars(build_argument_parser().parse_args()))
  File "/mnt/home/20236065/EE619-project03/MINE/ee619/train.py", line 115, in main
    action = pi.act(to_tensor(state))
  File "/mnt/home/20236065/EE619-project03/MINE/ee619/agent.py", line 82, in act
    action = Independent(Normal(loc, scale), 1).sample().squeeze(0).numpy()
  File "/mnt/home/20236065/anaconda3/lib/python3.10/site-packages/torch/distributions/normal.py", line 56, in __init__
    super().__init__(batch_shape, validate_args=validate_args)
  File "/mnt/home/20236065/anaconda3/lib/python3.10/site-packages/torch/distributions/distribution.py", line 62, in __init__
    raise ValueError(
ValueError: Expected parameter loc (Tensor of shape (1, 6)) of distribution Normal(loc: torch.Size([1, 6]), scale: torch.Size([1, 6])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan, nan, nan, nan, nan, nan]])
